kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: monitoring
  name: elasticsearch-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: elasticsearch-pv
