kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: monitoring
  name: elasticsearch-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/elasticsearch-pv
