apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials
type: Opaque
data:
  email_port: NTg3
  email_host_user: dGltaXNhcHJvamVrYXRAZ21haWwuY29t
  email_host_password: aXNhcHJvamVrYXQuMjI=
  email_use_tls: VHJ1ZQ==
